# Generated by Django 5.0.4 on 2024-04-03 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Published date')),
                ('image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Image')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
    ]
