# Generated by Django 4.1.13 on 2024-04-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='admin_answer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Admin'),
        ),
    ]
