# Generated by Django 4.1.13 on 2024-04-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_post_admin_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='admin_answer',
            field=models.CharField(max_length=255, verbose_name='Admin'),
        ),
    ]
